spring:
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/0THR5kGSWv
    username: 0THR5kGSWv
    password: O4OMpURtoC
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop